launch:
  ["ML", "FedAvg", "FedAvg_high_noises", "FedAvg_leave", "FedAvg_new_entry", "FedAvg_threshold_accuracy",
  "FedAvg_5_global_epoch", "FedAvg_non_IID", "FedAvg_10_client_agents_non_IID", "FedSGD", "FedSGD_non_IID",
  "FedPER", "FedPER_high_noises", "FedPER_non_IID"]

# all learning scenarios:
# "ML", "FedAvg", "FedAvg_high_noises", "FedAvg_leave", "FedAvg_new_entry", "FedAvg_threshold_accuracy",
# "FedAvg_5_global_epoch", "FedAvg_non_IID", "FedAvg_10_client_agents_non_IID", "FedSGD", "FedSGD_non_IID",
# "FedPER", "FedPER_high_noises", "FedPER_non_IID"